Add umount fail case

diff --git a/infra/base-images/base-runner/run_fuzzer b/infra/base-images/base-runner/run_fuzzer
--- a/infra/base-images/base-runner/run_fuzzer
+++ b/infra/base-images/base-runner/run_fuzzer
@@ -262,9 +262,14 @@ set -e
 cp -r $FUZZER_OUT $SAVED_FUZZER_OUT
 
 # Unmount tmpfs
+umounted=0
 for i in {1..30}; do
-	{ umount $FUZZER_OUT && break; } || { echo "[+] Umount failed ($i)" && sleep 10; }
+	{ umount $FUZZER_OUT && umounted=1; break; } || { echo "[+] Umount failed ($i)" && sleep 30; }
 done
+if [ $umounted = 0 ]; then
+	echo "[!] Cannot umount $FUZZER_OUT"
+	exit 1
+fi
 
 # Since the docker service runs as root we better make sure the user on the
 # host can r/w/x the files we create here.
